mocazzo_django/cart_app/urls.py
from django.urls import path
from . import views

app_name = 'cart_app'

urlpatterns = [

    path('/add/<int:pr_id>/', views.add_cart, name='addcart'),
    path('/cart', views.cart_details, name='cartdetails'),
    path('remove/<int:pro_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:pr_id>/', views.deletion, name='cart_delete'),

]

mocazzo_django/moc_app/urls.py
from django.urls import path

from moc_app import views
app_name = 'moc_app'
urlpatterns = [
    path('', views.index,name='index'),
    path('/<slug:c_slug>/<slug:p_slug>/',views.product,name='product'),
    path('/<slug:c_slug>/', views.index, name='product_of_cat'),



]

mocazzo_django/moc_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from moc_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index',include('moc_app.urls')),
    path('search',include('search_app.urls')),
    path('cart',include('cart_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mocazzo_django/search_app/urls.py
from django.urls import path

from . import views
app_name = 'search_app'
urlpatterns = [
    path('', views.search_view,name='searchview'),
    ]

mocazzo_django/cart_app/models.py
from django.db import models

from moc_app.models import Product


# Create your models here.

class Cart(models.Model):
    cartId = models.CharField(max_length=250,blank=True)
    date_added = models.DateTimeField(auto_now_add =True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']
    def __str__(self):
        return '{}'.format(self.cartId)
class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

mocazzo_django/moc_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category')
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def get_url(self):
        return reverse('moc_app:product_of_cat',args=[self.slug])

    def __str__(self):
        return self.name
class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product')
    price = models.DecimalField(max_digits=10,decimal_places=2)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def get_url(self):
        return reverse('moc_app:product',args=[self.category.slug,self.slug])


    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

mocazzo_django/search_app/models.py
from django.db import models

# Create your models here.

mocazzo_django/cart_app/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404

from cart_app.models import Cart, CartItem
from moc_app.models import Product
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
def add_cart(request,pr_id):
    product = Product.objects.get(id=pr_id)
    try:
        cart = Cart.objects.get(cartId=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cartId = _cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()


    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            cart = cart,
            quantity = 1

        )
        cart_item.save()
    return redirect('cart_app:cartdetails')

def cart_details(request,total=0,counter=0,cart_item=None):
    try:
        cart = Cart.objects.get(cartId = _cart_id(request))

        cart_items = CartItem.objects.filter(cart=cart,active=True)
        print(cart_items)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter,))

def cart_remove(request,pro_id):
    cart = Cart.objects.get(cartId=_cart_id(request))
    product = get_object_or_404(Product,id=pro_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cartdetails')

def deletion(request,pr_id):
    cart = Cart.objects.get(cartId=_cart_id(request))
    product = get_object_or_404(Product, id=pr_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cartdetails')

mocazzo_django/moc_app/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from moc_app.models import Category, Product


# Create your views here.
def index(request,c_slug=None):
    c_page = None
    products = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug= c_slug)
        products_list = Product.objects.all().filter(category=c_page)
    else:
        products_list = Product.objects.all()
    pagenator = Paginator(products_list,8)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products = pagenator.page(page)
    except(InvalidPage,EmptyPage):
        products = pagenator.page(pagenator.num_pages)


    return render(request,'index.html',{'category':c_page,'products':products})


def product(request,c_slug,p_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'product':product})

mocazzo_django/search_app/views.py
from django.shortcuts import render

# Create your views here.
from django.db.models import Q
from django.shortcuts import render

from moc_app.models import Product


# Create your views here.

def search_view(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

mocazzo_django/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block meta %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <!-- Google Fonts Roboto -->
   <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block link %}{% endblock %}
</head>
<body>
{% include 'header.html' %}
{% include 'nav.html'%}
{% block content %}{% endblock %}
{% include 'footer.html' %}
{% block script %}{% endblock %}
<script src="{% static '/js/popper.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}" ></script>

</body>
</html>

mocazzo_django/templates/cart.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}

<meta name="description" content="{{category.desc | truncatewords:155}}">


{% endblock %}

{% block title %}

shopping cart -mocajo online shop

{% endblock %}

{% block content %}
<section class="h-100 gradient-custom">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-header py-3">
            {% if not cart_items %}
<h5 class="mb-0">Your shopping cart is empty</h5>
            <br>
<p class="text-center">Please Click &nbsp; <a class="btn btn-success" href="{% url 'moc_app:index' %}">Here</a> &nbsp;To continue shopping</p>
</div>

{% else %}
<h5 class="mb-0">Your shopping cart</h5>

          </div>
          <div class="card-body">
            <!-- Single item -->
            <div class="row">
              {% for cart_item in cart_items %}
              <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                <!-- Image -->
                <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                  <img src="{{cart_item.product.img.url}}"
                    class="w-100" alt="{{cart_item.product.img.url}}" />
                  <a href="{{cart_item.product.get_url}}">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                  </a>
                </div>
                <!-- Image -->
              </div>

              <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                <!-- Data -->
                <p><strong>{{cart_item.product.name}}</strong></p>
                <p>SKU: {{cart_item.product.id}}</p>
                <p>Price: {{cart_item.product.price}}</p>
                <a href="{% url 'cart_app:cart_delete' cart_item.product.id %}" type="button" class="btn btn-primary btn-sm me-1 mb-2" data-mdb-toggle="tooltip"
                  title="Remove item">
                  <i class="fas fa-trash"></i>
                </a>

                <!-- Data -->
              </div>

              <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                <!-- Quantity -->
                <div class="d-flex mb-4" style="max-width: 300px">
                  <a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="btn btn-primary px-3 me-2">
                    <i class="fas fa-minus"></i>
                  </a>
                  <div class="form-outline text-center">
                    <p><strong>{{cart_item.quantity}}</strong></p>
                  </div>
{% if cart_item.quantity < cart_item.product.stock %}
                  <a href="{% url 'cart_app:addcart' cart_item.product.id %}" class="btn btn-primary px-3 ms-2">
                    <i class="fas fa-plus"></i>
                  </a>
                  {% endif %}
                </div>
                <!-- Quantity -->

                <!-- Price -->
                <p class="text-start text-md-center">
                  <strong>Total: ₹{{cart_item.sub_total}}</strong>
                </p>
                <!-- Price -->
              </div>
                    <hr>
              {% endfor %}

            </div>
            <!-- Single item -->

            <hr class="my-4" />

            <!-- Single item -->

            <!-- Single item -->
          </div>
        </div>
        <div class="card mb-4">
          <div class="card-body">
            <p><strong>Check out</strong></p>
            <p class="mb-0">Please Review your shopping Cart items Before proceeding with the order payment</p>
            <a href="{% url 'moc_app:index' %}" class="btn btn-secondary btn-block my_button">Continue shopping</a>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body">
            <p><strong>We accept</strong></p>
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
              alt="Visa" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
              alt="American Express" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
              alt="Mastercard" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.webp"
              alt="PayPal acceptance mark" />
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Summary</h5>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
                {% for cart_item in cart_items %}
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                {{cart_item.product.name}}
                <span>{{cart_item.sub_total}}</span>
              </li>
                {% endfor %}
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                Shipping
                <span>Free</span>
              </li>
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                <div>
                  <strong>Total amount</strong>
                  <strong>
                    <p class="mb-0">(including VAT)</p>
                  </strong>
                </div>
                <span><strong>₹{{total}}</strong></span>
              </li>
            </ul>

            <button type="button" class="btn btn-primary btn-lg btn-block">
              Go to checkout
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endif %}
{% endblock %}

mocazzo_django/templates/footer.html
{% load static %}


<footer class="text-center text-lg-start text-muted bg-primary mt-3">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start pt-4 pb-4">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-12 col-lg-12 col-sm-12 mb-2 text-center">
          <!-- Content -->

          <p class="mt-1 text-white ">
            © 2023 Copyright: Mocajo Pvt Lmt
          </p>
        </div>
        <!-- Grid column -->
      </div>
    </div>
  </section>
</footer>

mocazzo_django/templates/header.html
{% load static %}

    <header>
  <!-- Jumbotron -->
  <div class="py-3 text-center bg-white border-bottom">
    <div class="container">
      <div class="row gy-3">
        <!-- Left elements -->
        <div class="col-lg-2 col-sm-6 col-6 ">
          <a href="{% url 'moc_app:index' %}" target="_blank" class="float-start shadow">
            <img src="{% static 'img/log.png/' %}" height="35" />
          </a>
        </div>
        <!-- Left elements -->

        <!-- Center elements -->
        <div class="order-lg-last col-lg-5 col-sm-6 col-6">
          <div class="d-flex float-end shadow">

            <a href="{% url 'cart_app:cartdetails' %}" class="border rounded py-1 px-3 nav-link d-flex align-items-center" target="_blank">
              <i class="fas fa-shopping-cart m-1 me-md-2 "></i>
              <p class="d-none d-md-block mb-0 ">{{item_count}}</p>
            </a>
          </div>
        </div>
        <!-- Center elements -->

        <!-- Right elements -->
        <div class="col-lg-5 col-md-12 col-12">
          <div class="input-group float-center">
            <div class="form-outline">
                    <form class="d-flex" role="search" action="{% url 'search_app:searchview' %}" method="get">
          {% csrf_token %}
              <input type="search" name="q" id="form1" class="form-control shadow" />
              <label class="form-label" for="form1">Search</label>


            <button type="submit" class="btn btn-primary shadow-0">
              <i class="fas fa-search"></i>
            </button>
            </form>
              </div>
          </div>
        </div>
        <!-- Right elements -->
      </div>
    </div>
  </div>
  <!-- Jumbotron -->

  <!-- Heading -->

  <!-- Heading -->
</header>

mocazzo_django/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}

<meta name="description" content="{{category.desc | truncatewords:155}}">


{% endblock %}

{% block title %}

{{category.name}} -mocajo online shop

{% endblock %}

{% block content %}
<!-- cart + summary -->
<section class="bg-light my-5">
  <div class="container">
    <div class="row">
      <!-- cart -->
      <div class="col-lg-12">
        <div class="card border shadow-0">


          {% if category %}
            <h4 class="card-title mb-4">{{category.name}}</h4>
                <div class="text-center mx-4">
                    <img class="img-fluid w-100"  src="{{category.img.url}}" style="width:1100px; height:200px; margin-le " />
                </div>
            <div class="border-top pt-4 mx-4 mb-4">
            <p class="text-muted">
             {{category.desc}}
            </p>
          </div>

            {% else %}

            <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="{% static 'img/bn.jpg' %}" class="d-block w-100" alt="{% static 'img/bn.jpg' %}">
           <div class="carousel-caption  d-md-block border border-black p-3    bg-white rounded opacity-85">
        <h2 class="shadow-lg " style="font-family: 'Mooli', sans-serif; color:black; font-size: 50px; text-transform:uppercase;"><b>Moc<span class="bg-black " style="color:white;">azzo</span></b></h2>

           </div>
    </div>
   {% for i in links %}
    <div class="carousel-item">
      <img src="{{i.img.url}}" class="d-block w-100" alt="{{i.img.url}}">
         <div class="carousel-caption  d-md-block border border-black p-3 rounded opacity-85" style="background-color:#3ba272;">
        <h2 class="shadow-lg " style="font-family:sans-serif; color:black; font-size: 20px; text-transform:uppercase;"><b>{{i.name}}&nbsp;<span class="bg-black " style="color:white;">paintings</span></b></h2>

           </div>
    </div>
      {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>



          <div class="border-top pt-4 mx-4 mb-4">
            <p class="text-muted">
              "When a moment in front of me appears to be particularly special, whether it be by beauty or experience, I capture it. I usually find a reason to justify taking that photo - symmetry, or color or contrast - and it's my hope that my photography sheds light onto what I see and do on a daily basis."

            </p>
          </div>
            {% endif %}
        </div>
      </div>
  
      <!-- summary -->
    </div>
  </div>
</section>
<!-- cart + summary -->
<section>
  <div class="container my-5">
    {% if category is None %}
    <header class="mb-4">
      <h3>Recommended items</h3>
    </header>
{% endif %}
    <div class="row">
      {% for pro in products %}
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card px-4 border shadow-0 mb-4 mb-lg-0">
          <div class="mask px-2" style="height: 50px;">
            <p href="#"><i class="fas  text-primary fa-lg float-end pt-3 m-1 " style="font-size:10px ">stocks:{{pro.stock}}</i></p>
          </div>
          <a href="#" class="text-center">
            <img src="{{pro.img.url}}" class="card-img-top rounded-2" style="width: 218px;height: 211px;"/>
          </a>
          <div class="card-body d-flex flex-column pt-3 border-top">
            <a href="#" class="nav-link">{{pro.name}}</a>
            <div class="price-wrap mb-2">
              <strong class="">₹{{pro.price}}</strong>
            </div>
            <div class="card-footer d-flex align-items-end pt-3 px-0 pb-0 mt-auto">
              <a href="{{pro.get_url}}" class="btn btn-outline-primary w-100">View product</a>
            </div>
          </div>
        </div>
      </div>
{% endfor %}

    </div>
    <div class="mx-auto">
{% if products.paginator.num_pages > 1 %}

    <hr>

    <div class="text-center" style="padding-bottom:20px;">
{% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm">{{pg}}</a>
{% endfor %}

    </div>

    {% endif %}
  </div>
</section>
<!-- Recommended -->
{% endblock %}
<!-- Footer -->

mocazzo_django/templates/nav.html
{% load static %}


<div class="bg-dark">
    <div class="container py-4">
      <!-- Breadcrumb -->
      <nav class="d-flex">
        <h6 class="mb-0">
          {% if category is None %}
          <a href="{% url 'moc_app:index' %}" class="text-white-50">Home</a>
          {% else %}
          <a href="{% url 'moc_app:index' %}" class="text-white-50">Home</a>
          <span class="text-white-50 mx-2"> > </span>
          <a href="" class="text-white"><u>{{category.name}}</u></a> &nbsp;&nbsp;
          {% endif %}
          {% for i in links %}
          <span class="text-white-50 mx-2"> |</span>
          <a href="{{i.get_url}}" class="text-white"><u>&nbsp;{{i.name}}</u></a>

          {% endfor %}

        </h6>
      </nav>
      <!-- Breadcrumb -->
    </div>
  </div>

mocazzo_django/templates/product.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}

<meta name="description" content="{{product.desc | truncatewords:155}}">


{% endblock %}

{% block title %}

{{product.name}} -mocajo online shop

{% endblock %}
{% block link %}<link href="{% static '/css/prstyle.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
  <body>
    <main class="container">
<div class="row my_pr_row">
    <div class="">
        <p><a href="{% url 'moc_app:index' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
    </div>
</div>



      <!-- Left Column / Headphones Image -->

        <img  class="img-fluid pb-5  " src="{{product.img.url}}" alt="" style="height:500px; width:500px; padding-top:20px;">

      <!-- Right Column -->
      <div class="right-column ">

        <!-- Product Description -->
        <div class="product-description">

          <h1>{{product.name}}</h1>
          <p>{{product.desc}}</p>
        </div>

        <!-- Product Configuration -->


        <!-- Product Pricing -->
        <div class="product-price">
          <span>₹{{product.price}}</span>
          <a href="{% url 'cart_app:addcart' product.id %}" class="cart-btn">Add to cart</a>
        </div>
      </div>
    </main>
{% endblock %}
    <!-- Scripts -->
    {% block script %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js" charset="utf-8"></script>

    {% endblock %}

mocazzo_django/templates/search.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}

<meta name="description" content="{{category.desc | truncatewords:155}}">


{% endblock %}

{% block title %}

{{category.name}} -mocajo online shop

{% endblock %}

{% block content %}
<section>
  <div class="container my-5">

    <header class="mb-4">
      <h3>you have Searched For: {{query}}</h3>
    </header>

    <div class="row">
      {% for pro in products %}
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card px-4 border shadow-0 mb-4 mb-lg-0">
          <div class="mask px-2" style="height: 50px;">
            <p href="#"><i class="fas  text-primary fa-lg float-end pt-3 m-1 " style="font-size:10px ">stocks:{{pro.stock}}</i></p>
          </div>
          <a href="#" class="text-center">
            <img src="{{pro.img.url}}" class="card-img-top rounded-2" style="width: 218px;height: 211px;"/>
          </a>
          <div class="card-body d-flex flex-column pt-3 border-top">
            <a href="#" class="nav-link">{{pro.name}}</a>
            <div class="price-wrap mb-2">
              <strong class="">{{pro.price}}</strong>
            </div>
            <div class="card-footer d-flex align-items-end pt-3 px-0 pb-0 mt-auto">
              <a href="{{pro.get_url}}" class="btn btn-outline-primary w-100">View product</a>
            </div>
          </div>
        </div>
      </div>

{% endfor %}
    </div>
  </div>

</section>

{% endblock %}